    
version: '3'
services:
  app:
    container_name: bikesantiago
    restart: always
    build: ./server
    ports:
      - '3000:3000'
    links:
      - mongo
  cron_bikesantiago:
    build: ./cron
    entrypoint: sh /crontab.sh
    links:
      - app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'



# nginx:
#   build: ./nginx
#   links:
#     - server-john
#     - server-paul
#   ports:
#    - "3000:80"

# server-john:
#   build: ./server
#   expose:
#     - "3000"
#   environment:
#     - NAME=John

# server-paul:
#   build: ./server
#   expose:
#     - "3000"
#   environment:
#     - NAME=Paul

# mongo:
#   container_name: mongo
#   image: mongo
#   volumes:
#     - ./data:/data/db
#   ports:
#     - "27017:27017"
